### ISSUE TITLE
What is %session_name%?

### ISSUE THREAD

**Issue by hanfclippy** [AlluSoN/Bot_Mc_discord#36]

**Comment by Druzai** [comment]
It's the name of the server in bot configuration file `bot_config.yml`.
For example from this config:
```yml
servers_list:
- server_name: My minecraft server  # <- This one
  working_directory: \path\to\server\minecraft_server
  start_file_name: START.sh
  server_loading_time: 20
  enforce_offline_mode: false
```
Bot will create new terminal session with name `My_minecraft_server`. (spaces are replaced with underscores, because `screen` can't create session otherwise)
